export const mockCompanies = [
  {
    id: "1",
    name: "TCS (Tata Consultancy Services)",
    logo: "TCS",
    industry: "IT Services",
    size: "5000+",
    location: "Mumbai, Maharashtra",
    description: "Global IT services, consulting and business solutions organization that pioneers in digital transformation.",
    website: "https://www.tcs.com",
    culture: "Innovation • Excellence • Integrity",
    benefits: ["Health Insurance", "Stock Options", "Flexible Work", "Learning & Development"],
    openPositions: 245,
    rating: 4.2,
    reviews: 8934,
  },
  {
    id: "2",
    name: "Infosys",
    logo: "INF",
    industry: "IT Services",
    size: "5000+",
    location: "Bengaluru, Karnataka",
    description: "Global leader in next-generation digital services and consulting, enabling clients in more than 50 countries.",
    website: "https://www.infosys.com",
    culture: "Candid • Flexible • Innovative",
    benefits: ["Health Benefits", "Pension Plan", "Work from Home", "Education Reimbursement"],
    openPositions: 312,
    rating: 4.1,
    reviews: 7621,
  },
  {
    id: "3",
    name: "Wipro",
    logo: "WIP",
    industry: "IT Services",
    size: "5000+",
    location: "Bengaluru, Karnataka",
    description: "Leading global information technology, consulting and business process services company.",
    website: "https://www.wipro.com",
    culture: "Diversity • Sustainability • Innovation",
    benefits: ["Health Coverage", "Parental Leave", "Skill Development", "Performance Bonus"],
    openPositions: 198,
    rating: 4.0,
    reviews: 5847,
  },
  {
    id: "4",
    name: "HCL Technologies",
    logo: "HCL",
    industry: "IT Services",
    size: "5000+",
    location: "Noida, Uttar Pradesh",
    description: "Global technology company that helps enterprises reimagine their businesses through digital transformation.",
    website: "https://www.hcltech.com",
    culture: "Ideapreneurship • Mode 1-2-3 • Supercharging",
    benefits: ["Insurance", "Childcare", "Remote Work", "Learning Opportunities"],
    openPositions: 176,
    rating: 4.1,
    reviews: 4523,
  },
  {
    id: "5",
    name: "Accenture India",
    logo: "ACC",
    industry: "IT Services",
    size: "5000+",
    location: "Bengaluru, Karnataka",
    description: "Global professional services company that helps the world's leading businesses build digital core.",
    website: "https://www.accenture.com/in-en",
    culture: "Innovation • Inclusion • Integrity",
    benefits: ["Health Insurance", "Stock Purchase", "Flexible Leave", "Training Programs"],
    openPositions: 423,
    rating: 4.3,
    reviews: 8923,
  },
  {
    id: "6",
    name: "Tech Mahindra",
    logo: "TM",
    industry: "IT Services",
    size: "5000+",
    location: "Pune, Maharashtra",
    description: "IT services and consulting company that focuses on digital transformation and business renewal.",
    website: "https://www.techmahindra.com",
    culture: "Connected • Creative • Conscious",
    benefits: ["Health Cover", "Life Insurance", "Work from Home", "Career Growth"],
    openPositions: 145,
    rating: 3.9,
    reviews: 3421,
  },
  {
    id: "7",
    name: "Cognizant",
    logo: "COG",
    industry: "IT Services",
    size: "5000+",
    location: "Chennai, Tamil Nadu",
    description: "Modernizing technology, reimagining processes, and reimagining business models for clients.",
    website: "https://www.cognizant.com/in/en",
    culture: "Client Focus • Innovation • Collaboration",
    benefits: ["Health Benefits", "Retirement Plan", "Remote Options", "Tuition Reimbursement"],
    openPositions: 267,
    rating: 4.0,
    reviews: 6234,
  },
  {
    id: "8",
    name: "Capgemini India",
    logo: "CAP",
    industry: "IT Services",
    size: "5000+",
    location: "Mumbai, Maharashtra",
    description: "Global consulting, technology services, and digital transformation company.",
    website: "https://www.capgemini.com/in-en/",
    culture: "Diversity • Innovation • Responsibility",
    benefits: ["Insurance", "Flexible Hours", "Learning Budget", "International Mobility"],
    openPositions: 189,
    rating: 4.1,
    reviews: 4567,
  },
  {
    id: "9",
    name: "Mindtree",
    logo: "MT",
    industry: "IT Services",
    size: "1000-5000",
    location: "Bengaluru, Karnataka",
    description: "Digital transformation and technology services company, part of Larsen & Toubro Group.",
    website: "https://www.mindtree.com",
    culture: "Entrepreneurship • Expertise • Excellence",
    benefits: ["Health Insurance", "Stock Options", "Sabbatical", "Training"],
    openPositions: 98,
    rating: 4.2,
    reviews: 2134,
  },
  {
    id: "10",
    name: "L&T Infotech (LTI Mindtree)",
    logo: "LTI",
    industry: "IT Services",
    size: "1000-5000",
    location: "Mumbai, Maharashtra",
    description: "Global technology consulting and digital solutions company.",
    website: "https://www.ltimindtree.com",
    culture: "Innovation • Agility • Integrity",
    benefits: ["Health Cover", "Pension", "Flexible Work", "Skill Development"],
    openPositions: 134,
    rating: 4.0,
    reviews: 1876,
  },
  {
    id: "11",
    name: "Mphasis",
    logo: "MPH",
    industry: "IT Services",
    size: "1000-5000",
    location: "Bengaluru, Karnataka",
    description: "Leading cloud and cognitive services company that drives transformation.",
    website: "https://www.mphasis.com",
    culture: "Rapid • Fluid • Excited",
    benefits: ["Insurance", "Remote Work", "Learning", "Performance Bonus"],
    openPositions: 87,
    rating: 4.1,
    reviews: 1654,
  },
  {
    id: "12",
    name: "Persistent Systems",
    logo: "PSI",
    industry: "Software Development",
    size: "1000-5000",
    location: "Pune, Maharashtra",
    description: "Digital engineering and enterprise modernization company focused on technology services.",
    website: "https://www.persistent.com",
    culture: "Engineering Excellence • Innovation • Ownership",
    benefits: ["Health Benefits", "Stock Options", "Flexible Hours", "Learning Budget"],
    openPositions: 112,
    rating: 4.3,
    reviews: 1234,
  },
  {
    id: "13",
    name: "Larsen & Toubro (L&T) Technology Services",
    logo: "LTS",
    industry: "Engineering Services",
    size: "1000-5000",
    location: "Mumbai, Maharashtra",
    description: "Engineering, R&D, and digital solutions provider across multiple verticals.",
    website: "https://www.ltts.com",
    culture: "Engineering Prowess • Innovation • Safety",
    benefits: ["Health Insurance", "Pension Plan", "Training", "Travel Opportunities"],
    openPositions: 76,
    rating: 4.0,
    reviews: 987,
  },
  {
    id: "14",
    name: "Cyient",
    logo: "CYN",
    industry: "Engineering Services",
    size: "1000-5000",
    location: "Hyderabad, Telangana",
    description: "Engineering, manufacturing, and digital solutions partner to Fortune 500 companies.",
    website: "https://www.cyient.com",
    culture: "Engineering Excellence • Collaboration • Trust",
    benefits: ["Health Cover", "Life Insurance", "Learning", "Career Growth"],
    openPositions: 65,
    rating: 3.9,
    reviews: 765,
  },
  {
    id: "15",
    name: "Tech Aspect",
    logo: "TA",
    industry: "Software Development",
    size: "200-500",
    location: "Pune, Maharashtra",
    description: "Digital transformation and software product engineering services company.",
    website: "https://www.techaspect.com",
    culture: "Innovation • Quality • Customer Focus",
    benefits: ["Health Benefits", "Remote Work", "Training", "Flexible Hours"],
    openPositions: 45,
    rating: 4.2,
    reviews: 543,
  },
  {
    id: "16",
    name: "Zensar Technologies",
    logo: "ZEN",
    industry: "IT Services",
    size: "1000-5000",
    location: "Pune, Maharashtra",
    description: "Digital experiences, digital commerce, and technology services company.",
    website: "https://www.zensar.com",
    culture: "Creativity • Collaboration • Courage",
    benefits: ["Insurance", "Work from Home", "Learning Budget", "Bonuses"],
    openPositions: 58,
    rating: 4.0,
    reviews: 876,
  },
  {
    id: "17",
    name: "Birlasoft",
    logo: "BSF",
    industry: "IT Services",
    size: "1000-5000",
    location: "Noida, Uttar Pradesh",
    description: "Digital enterprise solutions provider focusing on manufacturing and banking sectors.",
    website: "https://www.birlasoft.com",
    culture: "Innovation • Customer Centricity • Excellence",
    benefits: ["Health Cover", "Life Insurance", "Training", "Growth"],
    openPositions: 67,
    rating: 3.8,
    reviews: 654,
  },
  {
    id: "18",
    name: "KPIT Technologies",
    logo: "KPIT",
    industry: "Automotive & Engineering",
    size: "500-1000",
    location: "Pune, Maharashtra",
    description: "Leading technology company specializing in automotive software and mobility solutions.",
    website: "https://www.kpit.com",
    culture: "Passion for Mobility • Innovation • Integrity",
    benefits: ["Health Insurance", "Stock Options", "Learning", "Flexible Work"],
    openPositions: 54,
    rating: 4.2,
    reviews: 876,
  },
  {
    id: "19",
    name: "Coforge",
    logo: "CFG",
    industry: "IT Services",
    size: "1000-5000",
    location: "Noida, Uttar Pradesh",
    description: "Global IT services and solutions company focused on digital transformation.",
    website: "https://www.coforge.com",
    culture: "Excellence • Innovation • Commitment",
    benefits: ["Health Benefits", "Remote Options", "Training", "Performance Bonus"],
    openPositions: 72,
    rating: 4.1,
    reviews: 987,
  },
  {
    id: "20",
    name: "NIIT Technologies",
    logo: "NIT",
    industry: "IT Services",
    size: "1000-5000",
    location: "Gurugram, Haryana",
    description: "Multi-geospatial artificial intelligence and analytics company.",
    website: "https://www.niittechnologies.com",
    culture: "Innovation • Customer Success • Agility",
    benefits: ["Insurance", "Learning Budget", "Work from Home", "Career Growth"],
    openPositions: 61,
    rating: 3.9,
    reviews: 765,
  },
  {
    id: "21",
    name: "Tata Elxsi",
    logo: "TEL",
    industry: "Design & Engineering",
    size: "500-1000",
    location: "Bengaluru, Karnataka",
    description: "Design and technology services company for automotive, broadcast, and communications.",
    website: "https://www.tataelxsi.com",
    culture: "Design Thinking • Innovation • Excellence",
    benefits: ["Health Cover", "Life Insurance", "Learning", "Creative Freedom"],
    openPositions: 48,
    rating: 4.3,
    reviews: 654,
  },
  {
    id: "22",
    name: "Tata Digital",
    logo: "TAD",
    industry: "E-commerce & Digital",
    size: "500-1000",
    location: "Mumbai, Maharashtra",
    description: "Digital products and services platform of Tata Group.",
    website: "https://www.tatadigital.com",
    culture: "Innovation • Customer First • Data-driven",
    benefits: ["Health Benefits", "Stock Options", "Remote Work", "Learning"],
    openPositions: 89,
    rating: 4.2,
    reviews: 432,
  },
  {
    id: "23",
    name: "Infosys BPM",
    logo: "BPM",
    industry: "BPO & Services",
    size: "1000-5000",
    location: "Bengaluru, Karnataka",
    description: "Business process management services arm of Infosys.",
    website: "https://www.infosysbpm.com",
    culture: "Process Excellence • Innovation • Customer Focus",
    benefits: ["Health Insurance", "Shift Allowances", "Training", "Growth"],
    openPositions: 156,
    rating: 3.8,
    reviews: 2341,
  },
  {
    id: "24",
    name: "Genpact India",
    logo: "GEN",
    industry: "BPO & Services",
    size: "5000+",
    location: "Gurugram, Haryana",
    description: "Global professional services firm delivering digital transformation.",
    website: "https://www.genpact.com/india",
    culture: "Lean • Digital • Transformation",
    benefits: ["Health Cover", "Life Insurance", "Flexible Work", "Learning"],
    openPositions: 178,
    rating: 4.0,
    reviews: 3456,
  },
  {
    id: "25",
    name: "Wipro Consumer Care",
    logo: "WCC",
    industry: "Consumer Goods & IT",
    size: "500-1000",
    location: "Kolkata, West Bengal",
    description: "Consumer care and lighting products company with digital services.",
    website: "https://www.wiproconsumer.com",
    culture: "Consumer Focus • Innovation • Sustainability",
    benefits: ["Health Benefits", "Travel Allowance", "Training", "Incentives"],
    openPositions: 34,
    rating: 4.1,
    reviews: 543,
  },
  {
    id: "26",
    name: "Tata Consultancy Services (TCS) - Digital",
    logo: "TCD",
    industry: "Digital Services",
    size: "1000-5000",
    location: "Pune, Maharashtra",
    description: "TCS's digital transformation and innovation unit.",
    website: "https://www.tcs.com",
    culture: "Innovation • Digital Prowess • Collaboration",
    benefits: ["Health Insurance", "Stock Options", "Flexible Work", "Learning"],
    openPositions: 134,
    rating: 4.3,
    reviews: 1234,
  },
  {
    id: "27",
    name: "Flipkart (Walmart India)",
    logo: "FLP",
    industry: "E-commerce",
    size: "5000+",
    location: "Bengaluru, Karnataka",
    description: "India's leading e-commerce marketplace and digital payments platform.",
    website: "https://www.flipkart.com",
    culture: "Customer Obsession • Bias for Action • Invent & Simplify",
    benefits: ["Health Insurance", "Stock Options", "Free Meals", "Gym"],
    openPositions: 289,
    rating: 4.4,
    reviews: 5678,
  },
  {
    id: "28",
    name: "Amazon India",
    logo: "AMZ",
    industry: "E-commerce & Cloud",
    size: "5000+",
    location: "Bengaluru, Karnataka",
    description: "Customer-centric company offering e-commerce, cloud computing, and digital services.",
    website: "https://www.amazon.jobs/en-gb/locations/india",
    culture: "Customer Obsession • Invent & Simplify • Are Right, A Lot",
    benefits: ["Health Insurance", "Stock Options", "Remote Work", "Learning"],
    openPositions: 456,
    rating: 4.2,
    reviews: 6789,
  },
  {
    id: "29",
    name: "Google India",
    logo: "GOO",
    industry: "Technology",
    size: "1000-5000",
    location: "Bengaluru, Karnataka",
    description: "World's most popular search engine with major R&D presence in India.",
    website: "https://careers.google.com/locations/india",
    culture: "Innovation • Inclusion • Excellence",
    benefits: ["Health Insurance", "Stock Options", "Wellness Programs", "Free Food"],
    openPositions: 234,
    rating: 4.6,
    reviews: 4321,
  },
  {
    id: "30",
    name: "Microsoft India",
    logo: "MSF",
    industry: "Technology",
    size: "5000+",
    location: "Hyderabad, Telangana",
    description: "Global technology leader with major engineering and operations center in India.",
    website: "https://careers.microsoft.com/locations/india",
    culture: "Innovation • Cloud First • Diversity",
    benefits: ["Health Insurance", "Stock Options", "Parental Leave", "Learning"],
    openPositions: 312,
    rating: 4.5,
    reviews: 5432,
  },
  {
    id: "31",
    name: "Adobe India",
    logo: "ADB",
    industry: "Software",
    size: "1000-5000",
    location: "Bengaluru, Karnataka",
    description: "Global leader in digital experience and marketing solutions.",
    website: "https://www.adobe.com/careers",
    culture: "Creativity • Innovation • Inclusion",
    benefits: ["Health Cover", "Stock Options", "Sabbatical", "Learning Budget"],
    openPositions: 145,
    rating: 4.5,
    reviews: 2345,
  },
  {
    id: "32",
    name: "Salesforce India",
    logo: "SFR",
    industry: "Cloud Computing",
    size: "1000-5000",
    location: "Bengaluru, Karnataka",
    description: "Global leader in CRM and enterprise cloud computing solutions.",
    website: "https://www.salesforce.com/company/careers",
    culture: "Customer Success • Innovation • Equality",
    benefits: ["Health Insurance", "Stock Options", "Volunteer Time Off", "Learning"],
    openPositions: 178,
    rating: 4.4,
    reviews: 1876,
  },
  {
    id: "33",
    name: "IBM India",
    logo: "IBM",
    industry: "Technology",
    size: "5000+",
    location: "Bengaluru, Karnataka",
    description: "Global hybrid cloud, AI, and enterprise solutions provider.",
    website: "https://www.ibm.com/careers/in",
    culture: "Innovation • Trust • Responsibility",
    benefits: ["Health Insurance", "Pension Plan", "Remote Work", "Training"],
    openPositions: 267,
    rating: 4.1,
    reviews: 4567,
  },
  {
    id: "34",
    name: "Oracle India",
    logo: "ORC",
    industry: "Enterprise Software",
    size: "1000-5000",
    location: "Bengaluru, Karnataka",
    description: "Complete suite of enterprise software, cloud, and hardware solutions.",
    website: "https://www.oracle.com/in/careers",
    culture: "Innovation • Customer Success • Excellence",
    benefits: ["Health Benefits", "Stock Options", "Flexible Hours", "Learning"],
    openPositions: 156,
    rating: 4.2,
    reviews: 2341,
  },
  {
    id: "35",
    name: "Intel India",
    logo: "INT",
    industry: "Semiconductors",
    size: "1000-5000",
    location: "Bengaluru, Karnataka",
    description: "World's largest semiconductor chip manufacturer with major R&D center in India.",
    website: "https://www.intel.com/content/www/us/en/jobs/locations/india.html",
    culture: "Innovation • Execution • Collaboration",
    benefits: ["Health Insurance", "Stock Options", "R&D Opportunities", "Training"],
    openPositions: 189,
    rating: 4.3,
    reviews: 3214,
  },
  {
    id: "36",
    name: "Qualcomm India",
    logo: "QCL",
    industry: "Semiconductors",
    size: "1000-5000",
    location: "Hyderabad, Telangana",
    description: "World leader in wireless technology and semiconductor design.",
    website: "https://www.qualcomm.com/company/careers",
    culture: "Innovation • Execution Excellence • Collaboration",
    benefits: ["Health Cover", "Stock Options", "R&D Labs", "Learning"],
    openPositions: 123,
    rating: 4.4,
    reviews: 1876,
  },
  {
    id: "37",
    name: "Cisco India",
    logo: "CSC",
    industry: "Networking",
    size: "1000-5000",
    location: "Bengaluru, Karnataka",
    description: "Global leader in networking, security, and collaboration solutions.",
    website: "https://www.cisco.com/c/en/us/about/careers.html",
    culture: "Innovation • Inclusion • Customer Success",
    benefits: ["Health Insurance", "Stock Options", "Flexible Work", "Wellness"],
    openPositions: 167,
    rating: 4.3,
    reviews: 2876,
  },
  {
    id: "38",
    name: "VMware India",
    logo: "VMW",
    industry: "Cloud & Virtualization",
    size: "1000-5000",
    location: "Bengaluru, Karnataka",
    description: "Leading cloud infrastructure and digital workspace technology provider.",
    website: "https://careers.vmware.com",
    culture: "Innovation • Courage • Community",
    benefits: ["Health Benefits", "Stock Options", "Sabbatical", "Learning"],
    openPositions: 98,
    rating: 4.3,
    reviews: 1654,
  },
  {
    id: "39",
    name: "SAP India",
    logo: "SAP",
    industry: "Enterprise Software",
    size: "1000-5000",
    location: "Bengaluru, Karnataka",
    description: "Global leader in enterprise application software and cloud solutions.",
    website: "https://www.sap.com/india/careers",
    culture: "Innovation • Customer Focus • Integrity",
    benefits: ["Health Insurance", "Stock Options", "Flexible Work", "Training"],
    openPositions: 134,
    rating: 4.2,
    reviews: 2134,
  },
  {
    id: "40",
    name: "Samsung India",
    logo: "SMG",
    industry: "Electronics & Tech",
    size: "5000+",
    location: "Noida, Uttar Pradesh",
    description: "Global leader in consumer electronics and semiconductor manufacturing.",
    website: "https://www.samsung.com/in/aboutsamsung/careers",
    culture: "Innovation • Quality • Excellence",
    benefits: ["Health Insurance", "Cafeteria", "Transport", "Training"],
    openPositions: 234,
    rating: 4.3,
    reviews: 3456,
  },
  {
    id: "41",
    name: "LG Electronics India",
    logo: "LGE",
    industry: "Electronics",
    size: "1000-5000",
    location: "Greater Noida, UP",
    description: "Leading consumer electronics and home appliances company.",
    website: "https://www.lg.com/in",
    culture: "Innovation • Quality • Customer Satisfaction",
    benefits: ["Health Cover", "Meal Allowance", "Transport", "Training"],
    openPositions: 67,
    rating: 4.0,
    reviews: 876,
  },
  {
    id: "42",
    name: "Sony India",
    logo: "SNY",
    industry: "Electronics & Entertainment",
    size: "500-1000",
    location: "Mumbai, Maharashtra",
    description: "Global entertainment and electronics company with strong India presence.",
    website: "https://www.sony.co.in",
    culture: "Innovation • Entertainment • Excellence",
    benefits: ["Health Insurance", "Entertainment Perks", "Training", "Growth"],
    openPositions: 45,
    rating: 4.1,
    reviews: 654,
  },
  {
    id: "43",
    name: "Panasonic India",
    logo: "PNC",
    industry: "Electronics",
    size: "500-1000",
    location: "Gurugram, Haryana",
    description: "Leading electronics and electrical equipment company.",
    website: "https://www.panasonic.com/in",
    culture: "Quality • Innovation • Harmony",
    benefits: ["Health Benefits", "Housing Allowance", "Training", "Incentives"],
    openPositions: 38,
    rating: 4.0,
    reviews: 543,
  },
  {
    id: "44",
    name: "Philips India",
    logo: "PHI",
    industry: "Healthcare Technology",
    size: "1000-5000",
    location: "Bengaluru, Karnataka",
    description: "Global leader in health technology with focus on cardiac care.",
    website: "https://www.philips.in",
    culture: "Innovation • Patient-focused • Sustainable",
    benefits: ["Health Insurance", "Wellness Programs", "Training", "Growth"],
    openPositions: 76,
    rating: 4.2,
    reviews: 987,
  },
  {
    id: "45",
    name: "Siemens India",
    logo: "SIE",
    industry: "Industrial Technology",
    size: "1000-5000",
    location: "Mumbai, Maharashtra",
    description: "Global technology company focused on electrification and automation.",
    website: "https://www.siemens.com/in/en/about-us/careers.html",
    culture: "Innovation • Excellence • Sustainability",
    benefits: ["Health Cover", "Life Insurance", "Training", "International Exposure"],
    openPositions: 89,
    rating: 4.2,
    reviews: 1234,
  },
  {
    id: "46",
    name: "ABB India",
    logo: "ABB",
    industry: "Industrial Automation",
    size: "1000-5000",
    location: "Bengaluru, Karnataka",
    description: "Global leader in electrification and automation technology.",
    website: "https://new.abb.com/india",
    culture: "Innovation • Safety • Sustainability",
    benefits: ["Health Insurance", "Pension", "Training", "Growth"],
    openPositions: 67,
    rating: 4.1,
    reviews: 876,
  },
  {
    id: "47",
    name: "Schneider Electric India",
    logo: "SCH",
    industry: "Energy Management",
    size: "1000-5000",
    location: "Hyderabad, Telangana",
    description: "Global specialist in energy management and industrial automation.",
    website: "https://www.se.com/in",
    culture: "Life is On • Innovation • Sustainability",
    benefits: ["Health Benefits", "Life Insurance", "Flexible Work", "Learning"],
    openPositions: 72,
    rating: 4.2,
    reviews: 987,
  },
  {
    id: "48",
    name: "Honeywell India",
    logo: "HON",
    industry: "Industrial Technology",
    size: "1000-5000",
    location: "Gurugram, Haryana",
    description: "Global diversified technology and manufacturing company.",
    website: "https://www.honeywell.com/india",
    culture: "Innovation • Quality • Safety",
    benefits: ["Health Insurance", "Stock Options", "Training", "Growth"],
    openPositions: 78,
    rating: 4.1,
    reviews: 1098,
  },
  {
    id: "49",
    name: "GE India",
    logo: "GE",
    industry: "Industrial Technology",
    size: "1000-5000",
    location: "Bengaluru, Karnataka",
    description: "Global industrial conglomerate with focus on aviation, healthcare, and energy.",
    website: "https://www.ge.com/in",
    culture: "Innovation • Integrity • Passion",
    benefits: ["Health Cover", "Life Insurance", "Training", "Relocation"],
    openPositions: 65,
    rating: 4.0,
    reviews: 876,
  },
  {
    id: "50",
    name: "Emerson India",
    logo: "EMR",
    industry: "Automation",
    size: "500-1000",
    location: "Pune, Maharashtra",
    description: "Global technology and engineering company providing automation solutions.",
    website: "https://www.emerson.com/in-en",
    culture: "Innovation • Integrity • Safety",
    benefits: ["Health Insurance", "Life Insurance", "Training", "Growth"],
    openPositions: 52,
    rating: 4.1,
    reviews: 654,
  },
  {
    id: "51",
    name: "Paytm",
    logo: "PYT",
    industry: "FinTech",
    size: "1000-5000",
    location: "Noida, Uttar Pradesh",
    description: "India's leading digital payments and financial services company.",
    website: "https://paytm.com/careers",
    culture: "Innovation • Speed • Customer First",
    benefits: ["Health Insurance", "Stock Options", "Free Meals", "Learning"],
    openPositions: 134,
    rating: 4.0,
    reviews: 1876,
  },
  {
    id: "52",
    name: "PhonePe",
    logo: "PPE",
    industry: "FinTech",
    size: "500-1000",
    location: "Bengaluru, Karnataka",
    description: "India's leading digital payments platform with UPI services.",
    website: "https://www.phonepe.com/careers",
    culture: "Innovation • Customer Focus • Excellence",
    benefits: ["Health Cover", "Stock Options", "Flexible Work", "Learning"],
    openPositions: 87,
    rating: 4.3,
    reviews: 987,
  },
  {
    id: "53",
    name: "Razorpay",
    logo: "RZR",
    industry: "FinTech",
    size: "500-1000",
    location: "Bengaluru, Karnataka",
    description: "Leading online payment gateway and banking solutions company.",
    website: "https://razorpay.com/careers",
    culture: "Ownership • Speed • Transparency",
    benefits: ["Health Insurance", "Stock Options", "Remote Work", "Learning"],
    openPositions: 98,
    rating: 4.4,
    reviews: 876,
  },
  {
    id: "54",
    name: "CRED",
    logo: "CRD",
    industry: "FinTech",
    size: "200-500",
    location: "Bengaluru, Karnataka",
    description: "Members-only club that rewards users for their credit card payments.",
    website: "https://cred.club/careers",
    culture: "Craftsmanship • High Standards • Innovation",
    benefits: ["Health Benefits", "Stock Options", "Free Meals", "Learning"],
    openPositions: 56,
    rating: 4.5,
    reviews: 543,
  },
  {
    id: "55",
    name: "PolicyBazaar",
    logo: "PBZ",
    industry: "InsurTech",
    size: "1000-5000",
    location: "Gurugram, Haryana",
    description: "India's largest insurance comparison platform.",
    website: "https://www.policybazaar.com/careers",
    culture: "Customer First • Innovation • Trust",
    benefits: ["Health Insurance", "Stock Options", "Learning", "Growth"],
    openPositions: 78,
    rating: 4.1,
    reviews: 1234,
  },
  {
    id: "56",
    name: "Upstox",
    logo: "UPX",
    industry: "FinTech",
    size: "200-500",
    location: "Mumbai, Maharashtra",
    description: "Leading discount brokerage firm with zero brokerage trading platform.",
    website: "https://upstox.com/careers",
    culture: "Innovation • Customer Focus • Integrity",
    benefits: ["Health Cover", "Stock Options", "Flexible Hours", "Learning"],
    openPositions: 45,
    rating: 4.2,
    reviews: 432,
  },
  {
    id: "57",
    name: "Zomato",
    logo: "ZOM",
    industry: "FoodTech",
    size: "1000-5000",
    location: "Gurugram, Haryana",
    description: "India's leading food delivery and dining-out platform.",
    website: "https://www.zomato.com/careers",
    culture: "Customer Obsession • Speed • Radical Transparency",
    benefits: ["Health Insurance", "Stock Options", "Free Meals", "Learning"],
    openPositions: 167,
    rating: 4.0,
    reviews: 2345,
  },
  {
    id: "58",
    name: "Swiggy",
    logo: "SWG",
    industry: "FoodTech",
    size: "1000-5000",
    location: "Bengaluru, Karnataka",
    description: "India's leading food delivery company with hyperlocal delivery.",
    website: "https://www.swiggy.com/careers",
    culture: "Customer Delight • Innovation • Speed",
    benefits: ["Health Cover", "Stock Options", "Flexible Work", "Learning"],
    openPositions: 145,
    rating: 3.9,
    reviews: 1987,
  },
  {
    id: "59",
    name: "Dunzo",
    logo: "DNZ",
    industry: "HyperLocal",
    size: "200-500",
    location: "Bengaluru, Karnataka",
    description: "Quick commerce and hyperlocal delivery platform.",
    website: "https://www.dunzo.com/careers",
    culture: "Speed • Customer Focus • Innovation",
    benefits: ["Health Insurance", "Stock Options", "Flexible Hours", "Growth"],
    openPositions: 54,
    rating: 3.8,
    reviews: 654,
  },
  {
    id: "60",
    name: "Ola Cabs",
    logo: "OLA",
    industry: "Mobility",
    size: "1000-5000",
    location: "Bengaluru, Karnataka",
    description: "India's leading mobility platform with ride-hailing and electric vehicles.",
    website: "https://www.olacabs.com/careers",
    culture: "Customer Obsession • Innovation • Sustainability",
    benefits: ["Health Benefits", "Stock Options", "Learning", "Growth"],
    openPositions: 112,
    rating: 3.9,
    reviews: 1567,
  },
  {
    id: "61",
    name: "Uber India",
    logo: "UBR",
    industry: "Mobility",
    size: "1000-5000",
    location: "Hyderabad, Telangana",
    description: "Global mobility platform with ridesharing and delivery services.",
    website: "https://www.uber.com/in/en/careers",
    culture: "Bold • Playbook • Doers",
    benefits: ["Health Insurance", "Stock Options", "Flexible Work", "Learning"],
    openPositions: 134,
    rating: 4.2,
    reviews: 1876,
  },
  {
    id: "62",
    name: "Meesho",
    logo: "MSH",
    industry: "Social Commerce",
    size: "500-1000",
    location: "Bengaluru, Karnataka",
    description: "India's fastest growing social commerce platform.",
    website: "https://meesho.io/careers",
    culture: "Democratize e-commerce • Innovation • Customer Focus",
    benefits: ["Health Cover", "Stock Options", "Remote Work", "Learning"],
    openPositions: 89,
    rating: 4.3,
    reviews: 765,
  },
  {
    id: "63",
    name: "Mamaearth",
    logo: "MAE",
    industry: "D2C Beauty",
    size: "200-500",
    location: "Gurugram, Haryana",
    description: "Natural and toxin-free baby and beauty products brand.",
    website: "https://www.mamaearth.in/careers",
    culture: "Natural • Customer First • Innovation",
    benefits: ["Health Insurance", "Free Products", "Growth", "Learning"],
    openPositions: 45,
    rating: 4.1,
    reviews: 654,
  },
  {
    id: "64",
    name: "BoAT (Imaginarium)",
    logo: "BOA",
    industry: "Consumer Electronics",
    size: "200-500",
    location: "Delhi, NCR",
    description: "Leading wearable and audio products brand in India.",
    website: "https://www.boat-lifestyle.com",
    culture: "Innovation • Consumer Focus • Excellence",
    benefits: ["Health Cover", "Incentives", "Growth", "Training"],
    openPositions: 38,
    rating: 4.0,
    reviews: 543,
  },
  {
    id: "65",
    name: "Droom",
    logo: "DRM",
    industry: "AutoTech",
    size: "200-500",
    location: "Gurugram, Haryana",
    description: "India's largest online automobile marketplace.",
    website: "https://www.droom.in/careers",
    culture: "Innovation • Trust • Excellence",
    benefits: ["Health Benefits", "Stock Options", "Learning", "Growth"],
    openPositions: 42,
    rating: 4.1,
    reviews: 432,
  },
  {
    id: "66",
    name: "CarDekho",
    logo: "CDK",
    industry: "AutoTech",
    size: "500-1000",
    location: "Jaipur, Rajasthan",
    description: "India's leading car buying and selling platform.",
    website: "https://www.cardekho.com/careers",
    culture: "Customer Focus • Innovation • Teamwork",
    benefits: ["Health Insurance", "Stock Options", "Flexible Hours", "Learning"],
    openPositions: 56,
    rating: 4.2,
    reviews: 654,
  },
  {
    id: "67",
    name: "UpGrad",
    logo: "UPG",
    industry: "EdTech",
    size: "1000-5000",
    location: "Mumbai, Maharashtra",
    description: "India's leading online education platform for higher Ed and professional courses.",
    website: "https://www.upgrad.com/careers",
    culture: "Learner First • Innovation • Excellence",
    benefits: ["Health Cover", "Stock Options", "Learning", "Growth"],
    openPositions: 98,
    rating: 4.2,
    reviews: 1234,
  },
  {
    id: "68",
    name: "Byju's (Think & Learn)",
    logo: "BYJ",
    industry: "EdTech",
    size: "5000+",
    location: "Bengaluru, Karnataka",
    description: "India's largest EdTech company revolutionizing learning.",
    website: "https://byjus.com/careers",
    culture: "Innovation • Learning • Impact",
    benefits: ["Health Insurance", "Stock Options", "Learning", "Growth"],
    openPositions: 187,
    rating: 3.8,
    reviews: 2345,
  },
  {
    id: "69",
    name: "Vedantu",
    logo: "VDU",
    industry: "EdTech",
    size: "500-1000",
    location: "Bengaluru, Karnataka",
    description: "Live online tutoring platform with interactive classes.",
    website: "https://www.vedantu.com/careers",
    culture: "Innovation • Education • Passion",
    benefits: ["Health Benefits", "Flexible Hours", "Learning", "Growth"],
    openPositions: 67,
    rating: 4.1,
    reviews: 876,
  },
  {
    id: "70",
    name: "Unacademy",
    logo: "UNA",
    industry: "EdTech",
    size: "1000-5000",
    location: "Bengaluru, Karnataka",
    description: "India's largest learning platform with live classes and video lessons.",
    website: "https://unacademy.com/careers",
    culture: "Learning • Innovation • Impact",
    benefits: ["Health Cover", "Stock Options", "Remote Work", "Learning"],
    openPositions: 112,
    rating: 4.0,
    reviews: 1567,
  },
  {
    id: "71",
    name: "Physics Wallah",
    logo: "PWH",
    industry: "EdTech",
    size: "1000-5000",
    location: "Noida, Uttar Pradesh",
    description: "Budget-friendly online education platform for competitive exams.",
    website: "https://physicswallah.com",
    culture: "Affordable Education • Innovation • Impact",
    benefits: ["Health Insurance", "Flexible Work", "Growth", "Learning"],
    openPositions: 145,
    rating: 4.2,
    reviews: 1987,
  },
  {
    id: "72",
    name: "Great Learning",
    logo: "GTL",
    industry: "EdTech",
    size: "200-500",
    location: "Gurugram, Haryana",
    description: "Professional learning platform for working professionals.",
    website: "https://www.greatlearning.com/careers",
    culture: "Learning • Excellence • Impact",
    benefits: ["Health Benefits", "Stock Options", "Learning", "Growth"],
    openPositions: 45,
    rating: 4.2,
    reviews: 543,
  },
  {
    id: "73",
    name: "Scaler Academy",
    logo: "SCL",
    industry: "EdTech",
    size: "200-500",
    location: "Bengaluru, Karnataka",
    description: "Tech education platform for working professionals.",
    website: "https://www.scaler.com/careers",
    culture: "Excellence • Innovation • Career Focus",
    benefits: ["Health Cover", "Stock Options", "Learning", "Growth"],
    openPositions: 56,
    rating: 4.4,
    reviews: 654,
  },
  {
    id: "74",
    name: "CRED (Already listed) - clone",
    logo: "CRD2",
    industry: "FinTech",
    size: "200-500",
    location: "Bengaluru, Karnataka",
    description: "Premium rewards and payments platform for credit card users.",
    website: "https://cred.club",
    culture: "Craftsmanship • High Standards • Speed",
    benefits: ["Health Benefits", "Stock Options", "Free Meals", "Learning"],
    openPositions: 34,
    rating: 4.5,
    reviews: 432,
  },
  {
    id: "75",
    name: "Credbee",
    logo: "CRB",
    industry: "EdTech",
    size: "50-200",
    location: "Hyderabad, Telangana",
    description: "Online education platform connecting students with expert tutors.",
    website: "https://www.credbee.com",
    culture: "Learning • Innovation • Impact",
    benefits: ["Health Insurance", "Flexible Hours", "Growth", "Training"],
    openPositions: 28,
    rating: 4.0,
    reviews: 345,
  },
  {
    id: "76",
    name: "Tata 1mg",
    logo: "TMG",
    industry: "HealthTech",
    size: "500-1000",
    location: "Gurugram, Haryana",
    description: "India's leading digital healthcare platform with pharmacy and diagnostics.",
    website: "https://www.1mg.com",
    culture: "Patient First • Innovation • Integrity",
    benefits: ["Health Cover", "Health Insurance", "Learning", "Growth"],
    openPositions: 67,
    rating: 4.2,
    reviews: 876,
  },
  {
    id: "77",
    name: "Practo",
    logo: "PRC",
    industry: "HealthTech",
    size: "500-1000",
    location: "Bengaluru, Karnataka",
    description: "India's leading healthcare appointments and digital health records platform.",
    website: "https://www.practo.com/careers",
    culture: "Innovation • Patient Care • Excellence",
    benefits: ["Health Insurance", "Stock Options", "Flexible Work", "Learning"],
    openPositions: 58,
    rating: 4.1,
    reviews: 765,
  },
  {
    id: "78",
    name: "Medlife",
    logo: "MDL",
    industry: "HealthTech",
    size: "200-500",
    location: "Bengaluru, Karnataka",
    description: "Online pharmacy and healthcare platform.",
    website: "https://www.medlife.com",
    culture: "Healthcare • Innovation • Trust",
    benefits: ["Health Benefits", "Flexible Hours", "Training", "Growth"],
    openPositions: 34,
    rating: 3.9,
    reviews: 432,
  },
  {
    id: "79",
    name: "Pharmeasy",
    logo: "PHE",
    industry: "HealthTech",
    size: "500-1000",
    location: "Mumbai, Maharashtra",
    description: "India's leading online medicine delivery platform.",
    website: "https://pharmeasy.in",
    culture: "Healthcare • Innovation • Customer Focus",
    benefits: ["Health Cover", "Stock Options", "Learning", "Growth"],
    openPositions: 52,
    rating: 4.0,
    reviews: 654,
  },
  {
    id: "80",
    name: "Innovacer",
    logo: "INV",
    industry: "HealthTech",
    size: "500-1000",
    location: "Bengaluru, Karnataka",
    description: "Healthcare data analytics and EMR solutions company.",
    website: "https://www.innovaccer.com",
    culture: "Innovation • Data-driven • Patient Focus",
    benefits: ["Health Insurance", "Stock Options", "Flexible Work", "Learning"],
    openPositions: 64,
    rating: 4.3,
    reviews: 567,
  },
  {
    id: "81",
    name: "Infosys (Already listed) - Regional",
    logo: "INF2",
    industry: "IT Services",
    size: "5000+",
    location: "Hyderabad, Telangana",
    description: "Global IT services company with major development center in Hyderabad.",
    website: "https://www.infosys.com",
    culture: "Candid • Flexible • Innovative",
    benefits: ["Health Benefits", "Pension", "Remote Work", "Education Reimbursement"],
    openPositions: 178,
    rating: 4.0,
    reviews: 3456,
  },
  {
    id: "82",
    name: "Wipro (Already listed) - Regional",
    logo: "WIP2",
    industry: "IT Services",
    size: "5000+",
    location: "Chennai, Tamil Nadu",
    description: "Global IT services company with operations center in Chennai.",
    website: "https://www.wipro.com",
    culture: "Diversity • Sustainability • Innovation",
    benefits: ["Health Coverage", "Parental Leave", "Skill Development", "Bonus"],
    openPositions: 123,
    rating: 3.9,
    reviews: 2345,
  },
  {
    id: "83",
    name: "HCL Technologies (Regional)",
    logo: "HCL2",
    industry: "IT Services",
    size: "5000+",
    location: "Chennai, Tamil Nadu",
    description: "Global technology company with regional center in Chennai.",
    website: "https://www.hcltech.com",
    culture: "Ideapreneurship • Mode 1-2-3 • Supercharging",
    benefits: ["Insurance", "Childcare", "Remote Work", "Learning"],
    openPositions: 134,
    rating: 4.0,
    reviews: 2341,
  },
  {
    id: "84",
    name: "TCS (Regional Center)",
    logo: "TCS2",
    industry: "IT Services",
    size: "5000+",
    location: "Kolkata, West Bengal",
    description: "Tata Consultancy Services with major BPO and IT center in Kolkata.",
    website: "https://www.tcs.com",
    culture: "Innovation • Excellence • Integrity",
    benefits: ["Health Insurance", "Stock Options", "Flexible Work", "Learning"],
    openPositions: 198,
    rating: 4.1,
    reviews: 3456,
  },
  {
    id: "85",
    name: "Tech Mahindra (Regional)",
    logo: "TM2",
    industry: "IT Services",
    size: "5000+",
    location: "Chennai, Tamil Nadu",
    description: "Tech Mahindra's southern operations hub in Chennai.",
    website: "https://www.techmahindra.com",
    culture: "Connected • Creative • Conscious",
    benefits: ["Health Cover", "Life Insurance", "Work from Home", "Career Growth"],
    openPositions: 89,
    rating: 3.8,
    reviews: 1678,
  },
  {
    id: "86",
    name: "Cognizant (Regional)",
    logo: "COG2",
    industry: "IT Services",
    size: "5000+",
    location: "Kolkata, West Bengal",
    description: "Cognizant's eastern India operations center.",
    website: "https://www.cognizant.com/in/en",
    culture: "Client Focus • Innovation • Collaboration",
    benefits: ["Health Benefits", "Retirement Plan", "Remote Options", "Tuition Reimbursement"],
    openPositions: 145,
    rating: 3.9,
    reviews: 2345,
  },
  {
    id: "87",
    name: "Accenture (Regional - Mumbai)",
    logo: "ACC2",
    industry: "IT Services",
    size: "5000+",
    location: "Mumbai, Maharashtra",
    description: "Accenture's financial services and operations hub in Mumbai.",
    website: "https://www.accenture.com/in-en",
    culture: "Innovation • Inclusion • Integrity",
    benefits: ["Health Insurance", "Stock Purchase", "Flexible Leave", "Training"],
    openPositions: 234,
    rating: 4.2,
    reviews: 3456,
  },
  {
    id: "88",
    name: "Genesys India",
    logo: "GNS",
    industry: "Customer Experience",
    size: "500-1000",
    location: "Bengaluru, Karnataka",
    description: "Global leader in cloud customer experience and contact center solutions.",
    website: "https://www.genesys.com/careers",
    culture: "Customer Experience • Innovation • Integrity",
    benefits: ["Health Insurance", "Stock Options", "Flexible Work", "Learning"],
    openPositions: 67,
    rating: 4.2,
    reviews: 567,
  },
  {
    id: "89",
    name: "ServiceNow India",
    logo: "SNV",
    industry: "Enterprise Software",
    size: "1000-5000",
    location: "Hyderabad, Telangana",
    description: "Global enterprise software platform for digital workflows.",
    website: "https://www.servicenow.com/careers",
    culture: "Innovation • Customer Success • Inclusion",
    benefits: ["Health Cover", "Stock Options", "Sabbatical", "Learning"],
    openPositions: 112,
    rating: 4.4,
    reviews: 1234,
  },
  {
    id: "90",
    name: "Workday India",
    logo: "WDY",
    industry: "Enterprise Software",
    size: "1000-5000",
    location: "Bengaluru, Karnataka",
    description: "Leading provider of enterprise cloud applications for finance and HR.",
    website: "https://www.workday.com/careers",
    culture: "Innovation • Customer Focused • Integrity",
    benefits: ["Health Insurance", "Stock Options", "Flexible Work", "Learning"],
    openPositions: 98,
    rating: 4.3,
    reviews: 876,
  },
  {
    id: "91",
    name: "Atlassian India",
    logo: "ATL",
    industry: "Software",
    size: "500-1000",
    location: "Bengaluru, Karnataka",
    description: "Global software company behind Jira, Confluence, and Trello.",
    website: "https://www.atlassian.com/careers",
    culture: "Open Company • No Bullshit • Build with Heart",
    benefits: ["Health Cover", "Stock Options", "Remote First", "Learning"],
    openPositions: 78,
    rating: 4.5,
    reviews: 654,
  },
  {
    id: "92",
    name: "Slack India",
    logo: "SLK",
    industry: "Enterprise Communication",
    size: "200-500",
    location: "Bengaluru, Karnataka",
    description: "Salesforce subsidiary providing workplace communication tools.",
    website: "https://slack.com/careers",
    culture: "Teamwork • Innovation • Inclusion",
    benefits: ["Health Benefits", "Stock Options", "Remote Work", "Wellness"],
    openPositions: 45,
    rating: 4.3,
    reviews: 432,
  },
  {
    id: "93",
    name: "Twitter/X India",
    logo: "XIN",
    industry: "Social Media",
    size: "100-500",
    location: "Hyderabad, Telangana",
    description: "Global social media platform with engineering hub in India.",
    website: "https://careers.x.com",
    culture: "Speed • Innovation • Transparency",
    benefits: ["Health Insurance", "Stock Options", "Remote Work", "Learning"],
    openPositions: 34,
    rating: 4.0,
    reviews: 345,
  },
  {
    id: "94",
    name: "LinkedIn India",
    logo: "LIN",
    industry: "Professional Network",
    size: "500-1000",
    location: "Bengaluru, Karnataka",
    description: "World's largest professional network with engineering center in India.",
    website: "https://careers.linkedin.com",
    culture: "Members First • Transformation • Integrity",
    benefits: ["Health Cover", "Stock Options", "Flexible Work", "Learning"],
    openPositions: 89,
    rating: 4.5,
    reviews: 765,
  },
  {
    id: "95",
    name: "Uber (Regional - Hyderabad)",
    logo: "UBR2",
    industry: "Mobility",
    size: "1000-5000",
    location: "Hyderabad, Telangana",
    description: "Global mobility platform's India engineering and operations hub.",
    website: "https://www.uber.com/in/en/careers",
    culture: "Bold • Playbook • Doers",
    benefits: ["Health Insurance", "Stock Options", "Flexible Work", "Learning"],
    openPositions: 87,
    rating: 4.1,
    reviews: 987,
  },
  {
    id: "96",
    name: "Flipkart (Regional - Hyderabad)",
    logo: "FLP2",
    industry: "E-commerce",
    size: "5000+",
    location: "Hyderabad, Telangana",
    description: "Flipkart's technology and operations center in Hyderabad.",
    website: "https://www.flipkart.com",
    culture: "Customer Obsession • Bias for Action • Invent & Simplify",
    benefits: ["Health Insurance", "Stock Options", "Free Meals", "Gym"],
    openPositions: 156,
    rating: 4.3,
    reviews: 2345,
  },
  {
    id: "97",
    name: "Amazon (Regional - Hyderabad)",
    logo: "AMZ2",
    industry: "E-commerce & Cloud",
    size: "5000+",
    location: "Hyderabad, Telangana",
    description: "Amazon's largest campus in India with AWS and e-commerce operations.",
    website: "https://amazon.jobs/en-gb/locations/india",
    culture: "Customer Obsession • Invent & Simplify • Are Right, A Lot",
    benefits: ["Health Insurance", "Stock Options", "Remote Work", "Learning"],
    openPositions: 234,
    rating: 4.1,
    reviews: 3456,
  },
  {
    id: "98",
    name: "Microsoft (Regional - Hyderabad)",
    logo: "MSF2",
    industry: "Technology",
    size: "5000+",
    location: "Hyderabad, Telangana",
    description: "Microsoft's largest campus in India with cloud and AI research.",
    website: "https://careers.microsoft.com/locations/india",
    culture: "Innovation • Cloud First • Diversity",
    benefits: ["Health Insurance", "Stock Options", "Parental Leave", "Learning"],
    openPositions: 198,
    rating: 4.4,
    reviews: 2876,
  },
  {
    id: "99",
    name: "Google (Regional - Hyderabad)",
    logo: "GOO2",
    industry: "Technology",
    size: "1000-5000",
    location: "Hyderabad, Telangana",
    description: "Google's campus in Hyderabad focusing on search and AI.",
    website: "https://careers.google.com/locations/india",
    culture: "Innovation • Inclusion • Excellence",
    benefits: ["Health Insurance", "Stock Options", "Wellness Programs", "Free Food"],
    openPositions: 145,
    rating: 4.5,
    reviews: 1987,
  },
  {
    id: "100",
    name: "Salesforce (Regional - Hyderabad)",
    logo: "SFR2",
    industry: "Cloud Computing",
    size: "1000-5000",
    location: "Hyderabad, Telangana",
    description: "Salesforce's India hub for engineering and customer success.",
    website: "https://www.salesforce.com/company/careers",
    culture: "Customer Success • Innovation • Equality",
    benefits: ["Health Insurance", "Stock Options", "Volunteer Time Off", "Learning"],
    openPositions: 112,
    rating: 4.3,
    reviews: 1234,
  },
  {
    id: "101",
    name: "Flipkart (Regional - Chennai)",
    logo: "FLP3",
    industry: "E-commerce",
    size: "5000+",
    location: "Chennai, Tamil Nadu",
    description: "Flipkart's southern operations and technology center.",
    website: "https://www.flipkart.com",
    culture: "Customer Obsession • Bias for Action • Invent & Simplify",
    benefits: ["Health Insurance", "Stock Options", "Free Meals", "Transport"],
    openPositions: 123,
    rating: 4.2,
    reviews: 1876,
  },
  {
    id: "102",
    name: "Cognizant (Regional - Chennai)",
    logo: "COG3",
    industry: "IT Services",
    size: "5000+",
    location: "Chennai, Tamil Nadu",
    description: "Cognizant's flagship delivery center in Chennai.",
    website: "https://www.cognizant.com/in/en",
    culture: "Client Focus • Innovation • Collaboration",
    benefits: ["Health Benefits", "Retirement Plan", "Remote Options", "Tuition Reimbursement"],
    openPositions: 198,
    rating: 4.0,
    reviews: 2987,
  },
  {
    id: "103",
    name: "TCS (Regional - Chennai)",
    logo: "TCS3",
    industry: "IT Services",
    size: "5000+",
    location: "Chennai, Tamil Nadu",
    description: "TCS's major IT services and BPO center in Chennai.",
    website: "https://www.tcs.com",
    culture: "Innovation • Excellence • Integrity",
    benefits: ["Health Insurance", "Stock Options", "Flexible Work", "Learning"],
    openPositions: 267,
    rating: 4.1,
    reviews: 4123,
  },
  {
    id: "104",
    name: "Infosys (Regional - Mysore)",
    logo: "INF3",
    industry: "IT Services",
    size: "5000+",
    location: "Mysuru, Karnataka",
    description: "Infosys's largest training campus and delivery center.",
    website: "https://www.infosys.com",
    culture: "Candid • Flexible • Innovative",
    benefits: ["Health Benefits", "Pension", "Remote Work", "Education Reimbursement"],
    openPositions: 156,
    rating: 4.0,
    reviews: 2345,
  },
  {
    id: "105",
    name: "Wipro (Regional - Kolkata)",
    logo: "WIP3",
    industry: "IT Services",
    size: "5000+",
    location: "Kolkata, West Bengal",
    description: "Wipro's eastern India operations and delivery center.",
    website: "https://www.wipro.com",
    culture: "Diversity • Sustainability • Innovation",
    benefits: ["Health Coverage", "Parental Leave", "Skill Development", "Bonus"],
    openPositions: 112,
    rating: 3.9,
    reviews: 1876,
  },
];

export const industries = [
  "IT Services",
  "Software Development",
  "E-commerce",
  "FinTech",
  "EdTech",
  "HealthTech",
  "Automotive & Engineering",
  "Electronics",
  "Cloud Computing",
  "Data Analytics",
  "Cybersecurity",
  "Telecommunications",
  "Banking & Financial Services",
  "Consulting",
  "Manufacturing",
];

export const companySizes = [
  { value: "1-10", label: "1-10 employees" },
  { value: "10-50", label: "10-50 employees" },
  { value: "50-200", label: "50-200 employees" },
  { value: "200-500", label: "200-500 employees" },
  { value: "500-1000", label: "500-1000 employees" },
  { value: "1000-5000", label: "1000-5000 employees" },
  { value: "5000+", label: "5000+ employees" },
];
